In [68]:
import numpy as np
import pandas as pd

In [69]:
train = pd.read_csv('/content/drive/MyDrive/train_s3TEQDk.csv')

In [70]:
train.head()

ID  Gender  Age  ... Avg_Account_Balance Is_Active Is_Lead
0  NNVBBKZB  Female   73  ...             1045696        No       0
1  IDD62UNG  Female   30  ...              581988        No       0
2  HD3DSEMC  Female   56  ...             1484315       Yes       0
3  BF3NC7KV    Male   34  ...              470454        No       0
4  TEASRWXV  Female   30  ...              886787        No       0

[5 rows x 11 columns]

In [71]:
train['Credit_Product'].fillna("Yes",inplace=True)

In [72]:
train.isnull().sum()

ID                     0
Gender                 0
Age                    0
Region_Code            0
Occupation             0
Channel_Code           0
Vintage                0
Credit_Product         0
Avg_Account_Balance    0
Is_Active              0
Is_Lead                0
dtype: int64

In [73]:
df_dummy = pd.get_dummies(train[["Gender","Occupation","Channel_Code","Credit_Product","Is_Active","Region_Code"]],drop_first=True)

In [74]:
train_dummy = pd.concat([train,df_dummy],axis=1)

In [75]:
train_dummy.head()

ID  Gender  ...  Region_Code_RG283 Region_Code_RG284
0  NNVBBKZB  Female  ...                  0                 0
1  IDD62UNG  Female  ...                  0                 0
2  HD3DSEMC  Female  ...                  0                 0
3  BF3NC7KV    Male  ...                  0                 0
4  TEASRWXV  Female  ...                  0                 0

[5 rows x 54 columns]

In [76]:
train_dummy.set_index("ID",inplace=True)

In [77]:
f_train = train_dummy.drop(columns=["Gender","Region_Code","Occupation","Channel_Code","Credit_Product","Is_Active"])

In [78]:
f_train.shape

(245725, 47)

In [79]:
f_train.sample(10)

Age  Vintage  ...  Region_Code_RG283  Region_Code_RG284
ID                      ...                                      
VZW7GGZE   26       25  ...                  0                  0
FTBA9A8B   84       98  ...                  0                  0
CAGTT44T   40       75  ...                  0                  0
KHZYJHDS   35       33  ...                  0                  1
ZFUZF3RD   29       32  ...                  0                  0
XX9LA4C6   53       97  ...                  0                  0
URA9RDWE   51       67  ...                  1                  0
Y3S7IC7Y   60       49  ...                  0                  0
PWPSWV7R   30       31  ...                  0                  0
QTY46NBQ   54       61  ...                  0                  0

[10 rows x 47 columns]

In [81]:
#Outliers handling in Avg_Account_Balance
min_thresold,max_thresold = f_train.Avg_Account_Balance.quantile([0.001,0.999])
min_thresold,max_thresold

(135292.30800000002, 7777345.0)

In [82]:
f_train[f_train.Avg_Account_Balance<min_thresold]

Age  Vintage  ...  Region_Code_RG283  Region_Code_RG284
ID                      ...                                      
SKV6MRO7   31       20  ...                  0                  0
HTKPZYP7   32       31  ...                  0                  0
CYWKKOWM   39       27  ...                  0                  0
GYVNAKSY   27       31  ...                  0                  0
R6RUKAPU   50       37  ...                  0                  0
...       ...      ...  ...                ...                ...
KDNMQFAX   57       25  ...                  0                  0
FANXYAWF   34       25  ...                  0                  0
3J4KPF7B   28       19  ...                  0                  0
KQJ2BVVU   31       25  ...                  0                  0
VP6DYWFV   27       21  ...                  0                  0

[246 rows x 47 columns]

In [83]:
f_train[f_train.Avg_Account_Balance>max_thresold]

Age  Vintage  ...  Region_Code_RG283  Region_Code_RG284
ID                      ...                                      
BDHVFC2R   41       19  ...                  1                  0
SQZAMYSZ   59       50  ...                  0                  0
PFPSA8QA   50       50  ...                  1                  0
KFU5MPQQ   43       19  ...                  0                  0
WT9KTHPE   53      110  ...                  0                  1
...       ...      ...  ...                ...                ...
SAAMQ2BZ   71      123  ...                  0                  0
AZXSSTEU   47       25  ...                  0                  1
ARV9RJEQ   66      109  ...                  1                  0
BDQF8JKD   25       15  ...                  0                  0
BG6UHJTS   32       13  ...                  0                  0

[245 rows x 47 columns]

In [84]:
f_train_no_outl = f_train[(f_train.Avg_Account_Balance<max_thresold) & (f_train.Avg_Account_Balance>min_thresold)]
f_train_no_outl.shape

(245232, 47)

In [85]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [86]:
X = f_train_no_outl.drop('Is_Lead',axis=1)
y = f_train_no_outl["Is_Lead"]

In [88]:
##Ovelsampling
from imblearn.over_sampling import RandomOverSampler

In [89]:
os = RandomOverSampler(random_state=42)

In [90]:
X_res, y_res = os.fit_resample(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [91]:
X_res.shape, y_res.shape

((374064, 46), (374064,))

In [93]:
from collections import Counter
print('Original dataset shape {}'.format(Counter(y)))
print('Resampled dataset shape {}'.format(Counter(y_res)))

Original dataset shape Counter({0: 187032, 1: 58200})
Resampled dataset shape Counter({0: 187032, 1: 187032})


In [94]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_res,y_res,random_state=0,test_size=0.2,shuffle=True)

In [57]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((299251, 46), (299251,), (74813, 46), (74813,))

In [96]:
X_train=pd.DataFrame(X_train)
X_train

0   1        2   3   4   5   6   7   ...  38  39  40  41  42  43  44  45
0       62  68   588717   0   1   0   0   1  ...   0   0   0   1   0   0   0   0
1       33  14   319332   0   0   1   0   0  ...   0   0   0   0   0   0   0   0
2       47  75   972387   0   0   0   1   0  ...   0   0   0   0   0   0   0   0
3       42  86   975395   0   0   0   1   1  ...   0   0   0   0   0   0   0   0
4       80  38  2845338   0   1   0   0   1  ...   0   0   0   0   0   0   0   1
...     ..  ..      ...  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..
299246  30  14   747288   0   0   1   0   0  ...   0   0   0   0   0   0   0   0
299247  36  15   688041   1   0   1   0   0  ...   0   0   0   0   0   0   0   0
299248  28  14   363476   0   1   0   0   0  ...   0   0   0   0   0   0   0   0
299249  41  21  1688935   0   0   0   1   1  ...   0   0   0   0   0   0   0   0
299250  47  73  1109554   1   0   0   0   1  ...   0   0   0   0   0   0   0   0

[299251 rows x 46 columns]

In [97]:
X_test = pd.DataFrame(X_test)
X_test

0    1        2   3   4   5   6   7   ...  38  39  40  41  42  43  44  45
0      46   68   536349   0   1   0   0   1  ...   0   0   0   0   0   0   0   0
1      36   26   601248   1   0   1   0   0  ...   0   0   0   0   0   0   0   0
2      27   21   649326   1   1   0   0   0  ...   0   0   0   1   0   0   0   0
3      62   26  1518170   0   1   0   0   1  ...   0   0   0   0   0   0   0   0
4      55   86   398728   0   0   0   1   0  ...   0   0   0   1   0   0   0   0
...    ..  ...      ...  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..
74808  38   31   635638   0   0   0   1   0  ...   0   0   0   0   0   0   0   1
74809  62  115  1056038   1   1   0   0   0  ...   0   0   0   0   0   0   1   0
74810  66   63  2049305   1   1   0   0   0  ...   0   0   0   0   0   0   0   0
74811  57  104   704532   0   1   0   0   0  ...   0   0   0   0   0   0   0   1
74812  47   37  1069931   0   1   0   0   0  ...   0   0   0   0   0   0   0   0

[74813 rows x 46 columns]

In [100]:
X_train.iloc[:,:3] = scaler.fit_transform(X_train.iloc[:,:3])
X_test.iloc[:,:3] = scaler.fit_transform(X_test.iloc[:,:3])

In [101]:
y_train

array([1, 1, 1, ..., 1, 0, 1])

In [102]:
y_test

array([1, 1, 0, ..., 1, 1, 0])

In [114]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

In [117]:
classifier = Sequential()
classifier.add(Dense(units=10, kernel_initializer='he_normal',activation='relu',input_dim=46))
#classifier.add(Dropout(0.3))
classifier.add(Dense(units=64, kernel_initializer='he_normal',activation='relu'))
#classifier.add(Dropout(0.4))
classifier.add(Dense(units=128, kernel_initializer='he_normal',activation='relu'))
classifier.add(Dense(units=256, kernel_initializer='he_normal',activation='relu'))
classifier.add(Dense(units=32, kernel_initializer='he_normal',activation='relu'))
#classifier.add(Dropout(0.2))
classifier.add(Dense(units=1,kernel_initializer='glorot_uniform',activation='sigmoid'))

In [118]:
classifier.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 10)                470       
_________________________________________________________________
dense_11 (Dense)             (None, 64)                704       
_________________________________________________________________
dense_12 (Dense)             (None, 128)               8320      
_________________________________________________________________
dense_13 (Dense)             (None, 256)               33024     
_________________________________________________________________
dense_14 (Dense)             (None, 32)                8224      
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 33        
Total params: 50,775
Trainable params: 50,775
Non-trainable params: 0
__________________________________________________

In [119]:
classifier.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

In [120]:
model_history=classifier.fit(X_train,y_train,validation_split=0.33, batch_size=16,epochs=10)

Epoch 1/10
12532/12532 [==============================] - 42s 3ms/step - loss: 0.5156 - accuracy: 0.7702 - val_loss: 0.4915 - val_accuracy: 0.7852
Epoch 2/10
12532/12532 [==============================] - 42s 3ms/step - loss: 0.4879 - accuracy: 0.7859 - val_loss: 0.4870 - val_accuracy: 0.7859
Epoch 3/10
12532/12532 [==============================] - 41s 3ms/step - loss: 0.4844 - accuracy: 0.7850 - val_loss: 0.4823 - val_accuracy: 0.7851
Epoch 4/10
12532/12532 [==============================] - 41s 3ms/step - loss: 0.4825 - accuracy: 0.7856 - val_loss: 0.4821 - val_accuracy: 0.7862
Epoch 5/10
12532/12532 [==============================] - 41s 3ms/step - loss: 0.4766 - accuracy: 0.7882 - val_loss: 0.4803 - val_accuracy: 0.7863
Epoch 6/10
12532/12532 [==============================] - 40s 3ms/step - loss: 0.4776 - accuracy: 0.7873 - val_loss: 0.4795 - val_accuracy: 0.7860
Epoch 7/10
12532/12532 [==============================] - 42s 3ms/step - loss: 0.4788 - accuracy: 0.7867 - val_loss: 0

In [121]:
scores = classifier.evaluate(X_test, y_test)
print(scores)

2338/2338 [==============================] - 4s 2ms/step - loss: 0.4773 - accuracy: 0.7894
[0.47728878259658813, 0.7893548011779785]


In [122]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [123]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [124]:
cm

array([[29338,  8158],
       [ 7601, 29716]])

In [125]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.7893547912795904

In [126]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,y_pred)

0.7893713991943011

In [183]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [187]:
rfc.score(X_train,y_train)

0.9999832916180731

In [184]:
rfc.score(X_test,y_test)

0.8771603865638324

In [185]:
rfc_predict = rfc.predict(X_test)

In [186]:
roc_auc_score(y_test,rfc_predict)

0.877233369149393

In [161]:
test = pd.read_csv('/content/drive/MyDrive/test_mSzZ8RL.csv')

In [162]:
test['Credit_Product'].fillna("Yes",inplace=True)

In [163]:
test_dummy = pd.get_dummies(test[["Gender","Occupation","Channel_Code","Credit_Product","Is_Active","Region_Code"]],drop_first=True)

In [164]:
test_dummy = pd.concat([test,test_dummy],axis=1)

In [165]:
test_dummy.set_index("ID",inplace=True)

In [166]:
f_test = test_dummy.drop(columns=["Gender","Region_Code","Occupation","Channel_Code","Credit_Product","Is_Active"])

In [167]:
f_test.head()

Age  Vintage  ...  Region_Code_RG283  Region_Code_RG284
ID                      ...                                      
VBENBARO   29       25  ...                  0                  0
CCMEWNKY   43       49  ...                  0                  0
VK3KGA9M   31       14  ...                  0                  0
TT8RPZVC   29       33  ...                  0                  0
SHQZEYTZ   29       19  ...                  0                  0

[5 rows x 46 columns]

In [168]:
f_test.iloc[:,:3] = scaler.fit_transform(f_test.iloc[:,:3])

In [169]:
f_test.shape

(105312, 46)

In [173]:
ann_pred = classifier.predict(f_test)

In [174]:

ann_pred

array([[0.101845  ],
       [0.6451349 ],
       [0.15677673],
       ...,
       [0.18992828],
       [0.43943664],
       [0.16112307]], dtype=float32)

In [175]:
for i in range(0,len(f_test)):
    if ann_pred[i]>=0.5:
        ann_pred[i] = int(1.0)
    else:
        ann_pred[i]=int(0.0)

In [176]:
ann_pred

array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [177]:
f_test["ann_pred"] = ann_pred

In [178]:
f_test

Age   Vintage  ...  Region_Code_RG284  ann_pred
ID                            ...                             
VBENBARO  0.081967  0.140625  ...                  0       0.0
CCMEWNKY  0.311475  0.328125  ...                  0       1.0
VK3KGA9M  0.114754  0.054688  ...                  0       0.0
TT8RPZVC  0.081967  0.203125  ...                  0       0.0
SHQZEYTZ  0.081967  0.093750  ...                  0       0.0
...            ...       ...  ...                ...       ...
DBENJOYI  0.459016  0.617188  ...                  0       1.0
CWQ72DWS  0.508197  0.617188  ...                  0       1.0
HDESC8GU  0.180328  0.062500  ...                  0       0.0
2PW4SFCA  0.475410  0.671875  ...                  0       0.0
F2NOYPPZ  0.049180  0.109375  ...                  0       0.0

[105312 rows x 47 columns]

In [ ]:
for i in range(0,len(f_test)):
    if lgbc_predictions[i]>=0.5:
        lgbc_predictions[i] = int(1.0)
    else:
        lgbc_predictions[i]=int(0.0)

In [137]:
f_test["ann_pred"] = ann_pred

In [138]:
f_test

Age  Vintage  ...  Region_Code_RG284  ann_pred
ID                      ...                             
VBENBARO   29       25  ...                  0       1.0
CCMEWNKY   43       49  ...                  0       1.0
VK3KGA9M   31       14  ...                  0       1.0
TT8RPZVC   29       33  ...                  0       1.0
SHQZEYTZ   29       19  ...                  0       1.0
...       ...      ...  ...                ...       ...
DBENJOYI   52       86  ...                  0       1.0
CWQ72DWS   55       86  ...                  0       1.0
HDESC8GU   35       15  ...                  0       1.0
2PW4SFCA   53       93  ...                  0       1.0
F2NOYPPZ   27       21  ...                  0       1.0

[105312 rows x 47 columns]

In [139]:
f_test.shape

(105312, 47)

In [179]:
f_test[f_test["ann_pred"] == 1.0].shape

(37498, 47)

In [181]:
output_ann = f_test["ann_pred"]

In [182]:
output_ann.to_csv('/content/drive/MyDrive/Kaggle/ann_predictions2.csv')

In [189]:
f_test = f_test.drop('ann_pred',axis=1)

In [190]:
rfc_pred = rfc.predict(f_test)

In [191]:
f_test["rfc_pred"] = rfc_pred

In [192]:
output_rfc = f_test["rfc_pred"]

In [193]:
output_rfc.to_csv('/content/drive/MyDrive/Kaggle/rfc_pred.csv')